# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='translator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10translator.proto\"J\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0c\x66romLanguage\x18\x02 \x01(\t\x12\x12\n\ntoLanguage\x18\x03 \x01(\t\"\x1e\n\x0eTranslateReply\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x15\x44\x65tectLanguageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\'\n\x13\x44\x65tectLanguageReply\x12\x10\n\x08language\x18\x01 \x01(\t2\x81\x01\n\nTranslator\x12\x31\n\tTranslate\x12\x11.TranslateRequest\x1a\x0f.TranslateReply\"\x00\x12@\n\x0e\x44\x65tectLanguage\x12\x16.DetectLanguageRequest\x1a\x14.DetectLanguageReply\"\x00\x62\x06proto3'
)




_TRANSLATEREQUEST = _descriptor.Descriptor(
  name='TranslateRequest',
  full_name='TranslateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='TranslateRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromLanguage', full_name='TranslateRequest.fromLanguage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toLanguage', full_name='TranslateRequest.toLanguage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=94,
)


_TRANSLATEREPLY = _descriptor.Descriptor(
  name='TranslateReply',
  full_name='TranslateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='TranslateReply.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=126,
)


_DETECTLANGUAGEREQUEST = _descriptor.Descriptor(
  name='DetectLanguageRequest',
  full_name='DetectLanguageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='DetectLanguageRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=165,
)


_DETECTLANGUAGEREPLY = _descriptor.Descriptor(
  name='DetectLanguageReply',
  full_name='DetectLanguageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='DetectLanguageReply.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['TranslateRequest'] = _TRANSLATEREQUEST
DESCRIPTOR.message_types_by_name['TranslateReply'] = _TRANSLATEREPLY
DESCRIPTOR.message_types_by_name['DetectLanguageRequest'] = _DETECTLANGUAGEREQUEST
DESCRIPTOR.message_types_by_name['DetectLanguageReply'] = _DETECTLANGUAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TranslateRequest = _reflection.GeneratedProtocolMessageType('TranslateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATEREQUEST,
  '__module__' : 'translator_pb2'
  # @@protoc_insertion_point(class_scope:TranslateRequest)
  })
_sym_db.RegisterMessage(TranslateRequest)

TranslateReply = _reflection.GeneratedProtocolMessageType('TranslateReply', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATEREPLY,
  '__module__' : 'translator_pb2'
  # @@protoc_insertion_point(class_scope:TranslateReply)
  })
_sym_db.RegisterMessage(TranslateReply)

DetectLanguageRequest = _reflection.GeneratedProtocolMessageType('DetectLanguageRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTLANGUAGEREQUEST,
  '__module__' : 'translator_pb2'
  # @@protoc_insertion_point(class_scope:DetectLanguageRequest)
  })
_sym_db.RegisterMessage(DetectLanguageRequest)

DetectLanguageReply = _reflection.GeneratedProtocolMessageType('DetectLanguageReply', (_message.Message,), {
  'DESCRIPTOR' : _DETECTLANGUAGEREPLY,
  '__module__' : 'translator_pb2'
  # @@protoc_insertion_point(class_scope:DetectLanguageReply)
  })
_sym_db.RegisterMessage(DetectLanguageReply)



_TRANSLATOR = _descriptor.ServiceDescriptor(
  name='Translator',
  full_name='Translator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=209,
  serialized_end=338,
  methods=[
  _descriptor.MethodDescriptor(
    name='Translate',
    full_name='Translator.Translate',
    index=0,
    containing_service=None,
    input_type=_TRANSLATEREQUEST,
    output_type=_TRANSLATEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DetectLanguage',
    full_name='Translator.DetectLanguage',
    index=1,
    containing_service=None,
    input_type=_DETECTLANGUAGEREQUEST,
    output_type=_DETECTLANGUAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSLATOR)

DESCRIPTOR.services_by_name['Translator'] = _TRANSLATOR

# @@protoc_insertion_point(module_scope)
